TOPICS = [
    "Travel",
    "Food",
    "Music",
    "Movies",
    "Books",
    "Sports",
    "Fitness",
    "Art",
    "Fashion",
    "Technology",
    "Cars",
    "Pets",
    "Nature",
    "Friends",
    "Relationships",
    "Work",
    "Money",
    "Politics",
    "Education",
    "Health",
    "Hobbies",
    "Entertainment",
    "Beauty",
    "Home",
    "Family",
    "Gaming",
    "Religion",
    "Culture",
    "Psychology",
    "Science",
    "Medicine",
    "Environment",
    "Social media",
    "Languages",
    "History",
    "Business",
    "Photography",
    "Writing",
    "Gardening",
    "Shopping",
    "Self-improvement",
    "News",
    "Astrology",
    "Philosophy",
    "Comedy",
    "Adventure",
    "Fantasy",
    "Mystery",
    "Romance",
    "Horror",
    "Thriller",
    "Action",
    "Drama",
    "Documentary",
    "Biography",
    "Autobiography",
    "Memoir",
    "Poetry",
    "Fiction",
    "Non-fiction",
    "Inspirational",
    "Motivational",
    "Self-help",
    "Science fiction",
    "Cyberpunk",
    "Post-apocalyptic",
    "Dystopian",
    "Utopian",
    "Steampunk",
    "Historical fiction",
    "Detective",
    "Crime",
    "Spy",
    "Military",
    "Adventure travel",
    "Cultural travel",
    "Backpacking",
    "Road trips",
    "Cruises",
    "Luxury travel",
    "Sustainable travel",
    "Street food",
    "Fine dining",
    "Fast food",
    "Gourmet",
    "Vegetarian",
    "Vegan",
    "Meat",
    "Seafood",
    "Chinese food",
    "Japanese food",
    "Italian food",
    "Mexican food",
    "Indian food",
    "Mediterranean food",
    "French food",
    "Thai food",
    "Korean food",
    "Greek food",
    "Middle Eastern food",
    "Jazz",
    "Blues",
    "Rock",
    "Pop",
    "Country",
    "Classical",
    "Electronic",
    "Hip hop",
    "Rap",
    "R&B",
    "Soul",
    "Folk",
    "World music",
    "Indie",
    "Alternative",
    "Metal",
    "Punk",
    "Grunge",
    "Reggae",
    "Ska",
    "Surfing",
    "Skateboarding",
    "Snowboarding",
    "Skiing",
    "Swimming",
    "Running",
    "Walking",
    "Cycling",
    "Yoga",
    "Pilates",
    "Weightlifting",
    "Crossfit",
    "Zumba",
    "Dance",
    "Ballet",
    "Modern dance",
    "Jazz dance",
    "Tap dance",
    "Ballroom dance",
    "Latin dance",
    "Street dance",
    "Painting",
    "Drawing",
    "Sculpture",
    "Ceramics",
    "Printmaking",
    "Calligraphy",
    "Graphic design",
    "Interior design",
    "Fashion design",
    "Web design",
    "Game design",
    "Architecture",
    "Industrial design",
    "Product design",
    "Photography",
    "Film",
    "TV shows",
    "Reality TV",
    "Sitcoms",
    "Dramas",
    "Documentaries",
    "Soap operas",
    "Game shows",
]